# Place this in the application directory created by this module
# name it config.toml
[Organization]
business_name="Old McDonald's Farm"

[GNUCash]
business_path="/home/user/thebusinessbooks.gnucash"
personal_path="/home/user/thepersonalbooks.gnucash"

[Valuation]
# Total number of corporate shares issued
Shares = 500

[Discounts]
# Used for calculating share value
# values are percentages
Assets = 80
Liabilities = 100
Cash = 70
Grain = 70
