# Place this in the application directory created by this module
# name it config.toml
[Organization]
business_name="Old McDonald's Farm"

[GNUCash]
business_path="/home/user/thebusinessbooks.gnucash"
personal_path="/home/user/thepersonalbooks.gnucash"

[Valuation]
# Total number of corporate shares issued
Shares = 500

[Discounts]
# Used for calculating share value
# values are percentages
Assets = 80
Liabilities = 100
Cash = 70
Grain = 70

["Elevator"]
elevator_name = "Farmers Coop"
loads_path = "/home/user/Downloads/download99999.CSV"

# used for scraping the loads CSV from elevator website
# need to store password in keyring using
# keyring set elevator [username] [password]
webpage = "https://mylocalgrainelevator.biz"
username = "my_username"
# look only for files matching the beginning characters
# specified in the file_match_pattern setting specified
file_match_pattern = "XYDL"

# used for storing images of receipts
joplin_db = "/home/user/.config/joplin-desktop/database.sqlite"
joplin_uri_prefix = "joplin://x-callback-url/openNote?id="
