# Use this text template in the Notes field of individual Accounts
# in GnuCash. The TOML elements will be parsed by the report generator
[Depreciation]
Cost = 420.00
Sec_179 = 50.00
Depreciation_Type = "Other"
Method = "MO S/L"
Years = 5
Date_in_Service = 2020-12-27T08:00:00.000000-06:00
